name       : flameshot
version    : 0.5.0
release    : 1
source     :
    - https://github.com/lupoDharkael/flameshot/archive/v0.5.0.tar.gz : 32d593c14c37286d9f64873c4ef9a07eb084723c92b2280d5c22152547c1e3f0
license    :
    - Apache-2.0
    - GPL-2.0
    - GPL-3.0
    - LAL-1.3
    - LGPL-3.0
component  : multimedia.graphics
summary    : Powerful yet simple to use screenshot software
description: |
    A program to capture screenshots.
    It includes CLI options as well as a GUI for capturing and annotating screenshots.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=packaging BASEDIR=$installdir
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 docs/bash-completion/flameshot -t $installdir/usr/share/bash-completion/completions


