name       : flameshot
version    : 0.8.5
release    : 8
source     :
    - https://github.com/flameshot-org/flameshot/archive/v0.8.5.tar.gz : f820c1f8cd464988cfcfc1af1fbcea2a3d0e5c4fb32accc3f54d93a8b5e1e890
license    :
    - Apache-2.0
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LAL-1.3
    - LGPL-3.0-or-later
component  : multimedia.graphics
summary    : Powerful yet simple to use screenshot software
description: |
    A program to capture screenshots. It includes CLI options as well as a GUI for capturing and annotating screenshots.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Svg)
rundeps    :
    - qt5-svg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
